import { useEffect, useState, type ReactNode } from 'react'
import { ArrowDown, ArrowUpRight, Check, ChevronDown, Code2, Database, ExternalLink, GitBranch, Mail, Menu, Moon, Server, Sun, Terminal, X } from 'lucide-react'
import { journey, principles, profile, skills } from './data/profile'
import { projects } from './data/projects'

const navItems = ['About', 'Skills', 'Projects', 'Journey', 'Experience', 'Learning', 'Contact']
const placeholder = (value: string) => value.startsWith('REPLACE_') || value.endsWith('_URL') || value === 'EMAIL'

function App() {
  const [dark, setDark] = useState(true)
  const [menuOpen, setMenuOpen] = useState(false)
  const [active, setActive] = useState('About')

  useEffect(() => {
    document.documentElement.dataset.theme = dark ? 'dark' : 'light'
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && setActive(entry.target.id)), { rootMargin: '-35% 0px -55% 0px' })
    navItems.forEach((item) => { const element = document.getElementById(item.toLowerCase()); if (element) observer.observe(element) })
    return () => observer.disconnect()
  }, [dark])

  const link = (url: string) => placeholder(url) ? undefined : url

  return <div className="site-shell">
    <header className="nav-wrap"><nav className="nav" aria-label="Primary navigation"><a className="brand" href="#top" aria-label="Priyabrata Barik home"><span className="brand-mark">PB</span><span>PB<span className="brand-dot">.</span></span></a><button className="menu-btn" aria-label={menuOpen ? 'Close menu' : 'Open menu'} onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X size={20} /> : <Menu size={20} />}</button><div className={`nav-links ${menuOpen ? 'open' : ''}`}>{navItems.map((item) => <a className={active === item.toLowerCase() ? 'active' : ''} href={`#${item.toLowerCase()}`} key={item} onClick={() => setMenuOpen(false)}>{item}</a>)}<button className="theme-btn" onClick={() => setDark(!dark)} aria-label={`Switch to ${dark ? 'light' : 'dark'} theme`}>{dark ? <Sun size={17} /> : <Moon size={17} />}</button></div></nav></header>

    <main id="top">
      <section className="hero section-pad"><div className="hero-copy"><p className="kicker"><span className="pulse" /> Available for meaningful engineering conversations</p><h1>Engineering the path<br /><em>from idea to impact.</em></h1><p className="hero-lede">{profile.role} building reliable, automated and scalable engineering platforms using cloud technologies, Infrastructure as Code, CI/CD, Kubernetes and automation.</p><p className="hero-note">14+ years of enterprise IT experience across database, platform and DevOps engineering.</p><div className="hero-actions"><a className="button button-primary" href="#projects">View projects <ArrowDown size={17} /></a><a className="text-link" href={link(profile.github) || '#contact'}>GitHub <ArrowUpRight size={16} /></a><a className="text-link" href={link(profile.linkedin) || '#contact'}>LinkedIn <ArrowUpRight size={16} /></a><a className="text-link" href={link(profile.resume) || '#contact'}>Resume <ArrowUpRight size={16} /></a></div></div><InfrastructureVisual /></section>

      <section id="about" className="section-pad section-line"><SectionLabel number="01" label="Profile" /><div className="split-heading"><h2>Deep roots.<br /><span>Modern reach.</span></h2><div className="about-copy"><p className="lead">My career has evolved through database engineering, platform engineering, DevOps, cloud infrastructure, automation and modern platform engineering.</p><p>That path matters. It means I understand the systems underneath the platform, the controls around delivery, and the developer experience that makes good engineering repeatable. Today, my focus spans DevOps, cloud, CI/CD, Infrastructure as Code, Kubernetes, security integration, Python and AI/ML infrastructure.</p></div></div><div className="about-strip"><div><strong>14+</strong><span>years in enterprise IT</span></div><div><strong>01 → 06</strong><span>an evolving engineering journey</span></div><div><strong>∞</strong><span>curiosity for what comes next</span></div></div></section>

      <section id="skills" className="section-pad section-dark"><SectionLabel number="02" label="Capabilities" /><div className="section-intro"><h2>The toolkit behind<br /><span>the platform.</span></h2><p>Technology is useful when it creates leverage. These are the building blocks I bring together to make systems more reliable and teams more effective.</p></div><div className="skills-grid">{Object.entries(skills).map(([category, items], index) => <article className={`skill-card skill-${index}`} key={category}><span className="skill-index">0{index + 1}</span><h3>{category}</h3><div className="tag-list">{items.map((item) => <span key={item}>{item}</span>)}</div></article>)}</div></section>

      <section id="projects" className="section-pad section-line"><SectionLabel number="03" label="Selected work" /><div className="section-intro projects-intro"><h2>Proof, in<br /><span>progress.</span></h2><p>Selected explorations and engineering projects live in their own repositories. The portfolio is the map; the code is elsewhere.</p></div><div className="project-grid">{projects.map((project, index) => <article className="project-card" key={project.title}><div className="project-top"><span className="project-number">0{index + 1}</span>{project.status && <span className="status"><span />{project.status}</span>}</div><p className="eyebrow">{project.eyebrow}</p><h3>{project.title}</h3><p>{project.description}</p><div className="tag-list">{project.tags.map((tag) => <span key={tag}>{tag}</span>)}</div><a className="card-link" href={link(project.url) || '#contact'}>View on GitHub <ExternalLink size={15} /></a></article>)}</div></section>

      <section id="journey" className="section-pad journey-section"><SectionLabel number="04" label="The long view" /><div className="section-intro"><h2>My engineering<br /><span>journey.</span></h2><p>Each chapter added a new lens. Together, they form a practical understanding of how enterprise systems are built, changed and operated.</p></div><div className="journey-grid">{journey.map(([number, title, items], index) => <article className={`journey-step ${index === journey.length - 1 ? 'journey-future' : ''}`} key={title}><span className="step-number">{number}</span><div><h3>{title}</h3><ul>{items.map((item) => <li key={item}>{item}</li>)}</ul></div>{index < journey.length - 1 && <ChevronDown className="journey-arrow" size={19} />}</article>)}</div></section>

      <section className="section-pad approach-section"><SectionLabel number="05" label="Working principles" /><div className="approach-layout"><div><h2>How I<br /><span>build.</span></h2><div className="flow-list">{['Developer', 'Git / GitHub', 'CI/CD', 'Build & Test', 'Security & Quality', 'Infrastructure as Code', 'Cloud / Kubernetes', 'Deployment', 'Monitoring & Improvement'].map((item, index) => <div key={item} className="flow-item"><span>{String(index + 1).padStart(2, '0')}</span>{item}{index < 8 && <ArrowDown size={14} />}</div>)}</div></div><div className="principles-grid">{principles.map(([title, text]) => <article key={title}><Check size={17} /><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>

      <section className="section-pad architecture-section"><SectionLabel number="06" label="System thinking" /><div className="section-intro"><h2>From commit<br /><span>to cluster.</span></h2><p>A responsive view of the delivery path: automated, observable and designed to make quality part of the flow.</p></div><div className="architecture"><ArchitectureNode icon={<Terminal />} title="Developer" text="Intent & change" /><div className="arch-line" /><ArchitectureNode icon={<GitBranch />} title="Git / GitHub" text="Versioned source" /><div className="arch-line" /><ArchitectureNode icon={<Code2 />} title="CI/CD pipeline" text="Actions / Jenkins" /><div className="arch-line" /><ArchitectureNode icon={<Check />} title="Quality gates" text="Security & review" /><div className="arch-line" /><ArchitectureNode icon={<Server />} title="Terraform / Ansible" text="Provision & configure" /><div className="arch-line" /><ArchitectureNode icon={<Database />} title="AWS / GCP / K8s" text="Operate & improve" /></div></section>

      <section id="experience" className="section-pad section-line"><SectionLabel number="07" label="Experience" /><div className="split-heading"><h2>Systems<br /><span>with context.</span></h2><div className="experience-list"><ExperienceItem current title="Senior DevOps & Platform Engineer" company="[Company Name]" dates="[Start Date] – Present" tags={['DevOps', 'Platform Engineering', 'AWS', 'Terraform', 'Ansible', 'CI/CD', 'Kubernetes', 'Python']} /><ExperienceItem title="Database / Platform Engineering" company="[Company Name]" dates="[Dates]" tags={['IBM Netezza', 'PostgreSQL', 'Microsoft SQL Server', 'Oracle', 'Liquibase', 'Database engineering']} /></div></div></section>

      <section id="learning" className="section-pad learning-section"><SectionLabel number="08" label="Forward motion" /><div className="section-intro"><h2>Where I’m going<br /><span>next.</span></h2><p>These are active learning and future-focus areas, not a claim of completed professional experience. The map keeps moving.</p></div><div className="roadmap">{[['01', 'Platform Engineering', 'Advanced platform architecture and developer platforms.'], ['02', 'Cloud', 'AWS and GCP architecture.'], ['03', 'Kubernetes', 'Cloud-native infrastructure and orchestration.'], ['04', 'Python', 'Automation and platform tooling.'], ['05', 'AI/ML Infrastructure', 'Infrastructure supporting machine learning workloads.'], ['06', 'MLOps', 'CI/CD, automation and deployment for machine learning systems.']].map(([number, title, text]) => <article key={title}><span>{number}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>

      <section id="contact" className="contact-section section-pad"><div className="contact-inner"><SectionLabel number="09" label="Open channel" light /><h2>Let’s build what<br /><em>comes next.</em></h2><p>Interested in DevOps, Platform Engineering, Cloud, Automation or technology? Let’s connect.</p><div className="contact-actions"><a className="button button-light" href={link(profile.linkedin) || '#top'}><ExternalLink size={17} /> LinkedIn</a><a className="button button-outline" href={link(profile.github) || '#top'}><GitBranch size={17} /> GitHub</a><a className="button button-outline" href={profile.email === 'EMAIL' ? '#top' : `mailto:${profile.email}`}><Mail size={17} /> Email</a></div></div></section>
    </main><footer><span>© {new Date().getFullYear()} Priyabrata Barik</span><span>Built with intent · React + TypeScript</span></footer>
  </div>
}

function SectionLabel({ number, label, light = false }: { number: string; label: string; light?: boolean }) { return <div className={`section-label ${light ? 'light' : ''}`}><span>{number}</span><span>{label}</span></div> }
function ArchitectureNode({ icon, title, text }: { icon: ReactNode; title: string; text: string }) { return <div className="arch-node"><div className="arch-icon">{icon}</div><div><strong>{title}</strong><span>{text}</span></div></div> }
function ExperienceItem({ current, title, company, dates, tags }: { current?: boolean; title: string; company: string; dates: string; tags: string[] }) { return <article className="experience-item"><div className="experience-title"><span className={current ? 'current-dot' : ''} /><div><h3>{title}</h3><p>{company} · {dates}</p></div></div><div className="tag-list">{tags.map((tag) => <span key={tag}>{tag}</span>)}</div></article> }
function InfrastructureVisual() { return <div className="infra-visual" aria-label="Cloud infrastructure delivery flow"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="infra-core"><span className="core-icon">⌁</span><strong>platform</strong><span>as a system</span></div>{[['cloud', 'cloud'], ['iac', 'IaC'], ['cicd', 'CI/CD'], ['k8s', 'K8s']].map(([className, text]) => <div className={`infra-node ${className}`} key={text}><span>{text}</span><i /></div>)}<div className="infra-caption"><span>01</span> Cloud → IaC → CI/CD → Kubernetes</div></div> }

export default App